### ISSUE TITLE
AI UK 2023 Preparations

### ISSUE THREAD

**Issue by JimCircadian** [icenet-ai/icenet-project#39]
High level list of things to prepare, owners in brackets: 

* [x] Organise setup w/Turing (@JimCircadian / @aldenc)
  * [x] 4 x plinths
  * [x] 8 x stools
  * [x] Plasma connectivity
  * [x] Discussion around 500mA limit over a four way 
* [x] Posters (@JimCircadian)
  * [x] Banner poster 
  * [x] Demo times / descriptions poster (one each side of screen)
  * [x] Find out about fixings
* [x] Preparation of demo narratives (all of these are new issues in new repository)
  * *Probably want to limit a narrative runthrough to 5-10 minutes)*
  * [x] Create new repo for aiuk23 (publishable via zenodo after event)
  * [x] [Motivation and overview for what we're doing](https://github.com/icenet-ai/aiuk-2023/issues/1)
  * [x] [SIC cycling video](https://github.com/icenet-ai/aiuk-2023/issues/2) (both hemispheres together / input variables visualised)
  * [x] **Narrative overviews for each individual** - discuss and highlight single owners for each (@JimCircadian) - see each issue
  * [x] [Machine learning research and validation](https://github.com/icenet-ai/aiuk-2023/issues/3) (@rchan26)
  * [x] [Conservation and research use](https://github.com/icenet-ai/aiuk-2023/issues/4) (@EllieBowler)
  * [x] [Infrastructure / software engineering](https://github.com/icenet-ai/aiuk-2023/issues/5) (@JimCircadian)
  * [x] End user usage (@JimCircadian)
* [x] Explore plasma screen usage (@JimCircadian)
  * [x] Get sea ice heavy promo video
  * [x] Ensure everyone can run their demos
* [x] Book Feb meeting (@JimCircadian)
* [x] Promotion: @JimCircadian get in contact with BAS communications
  * Ensure BAS comms link in with Turing / research engineering account (e.g. through twitter handle links)
  * @gecoombs to check in on existing conversations with comms
  * Pick up [twitter](https://twitter.com/turinginst/status/1617886246667264002?s=20) posts existing

**Comment by JimCircadian** [comment]
Discussion points from meeting:

* Need to check screens are provided with external cables, suggestion is that they're intending USB sticks to be used to display items which won't work for us - HDMI and USBc should be available, we can request spec sheet
* Furniture and equipment can be bought separately, but the venue will need to be liaised with for deliveries.
* **10th February** deadline should be used to request everything from `AIUK@whitespacexpo.com`

**Comment by JimCircadian** [comment]
* Connect plasma to individual laptop
* Banner poster prepared, demo poster not required
* QR codes for "menus" - demos that are available?
* Revised themes:
  * Research usage
  * ML research and validation
  * Software infrastructure
  * Operational usage and integrations
* Use slides and/or notebooks in a dedicated github repository
  * Include motivators and background for SIC prediction
* Tickets half sold, perhaps promote personally

**Comment by JimCircadian** [comment]
@ots22 @aldenc @rchan26 @EllieBowler @MartinSJRogers @ampersandmcd @tom-andersson The repository for [AI UK 2023 is here](https://github.com/icenet-ai/aiuk-2023) and license set up to OGL (which is an equivalent to CC-BY-4.0)

**Comment by JimCircadian** [comment]
We only had 4 stools, but rarely needed them. It was all a lot of fun.. 

Closing this project issue, big thanks @EllieBowler @rchan26 @tom-andersson @MartinSJRogers @scotthosking @aldenc @ampersandmcd @ots22  for your efforts both during and before the event, really much appreciated and totally living up to the "IceNet dream team" moniker I've decided to label y'all with!
